//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NBAStatistics.Data.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class NBAStatisticsEntities : DbContext
    {
        public NBAStatisticsEntities()
            : base("name=NBAStatisticsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Arena> Arenas { get; set; }
        public virtual DbSet<City> Cities { get; set; }
        public virtual DbSet<Conference> Conferences { get; set; }
        public virtual DbSet<Country> Countries { get; set; }
        public virtual DbSet<HeadCoach> HeadCoaches { get; set; }
        public virtual DbSet<Player> Players { get; set; }
        public virtual DbSet<School> Schools { get; set; }
        public virtual DbSet<StandingsByDay> StandingsByDays { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<Team> Teams { get; set; }
    }
}
