//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NBAStatistics.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StandingsByDay
    {
        public int Id { get; set; }
        public System.DateTime Date { get; set; }
        public int TeamId { get; set; }
        public int SeasonId { get; set; }
        public int ConferenceId { get; set; }
        public byte Games { get; set; }
        public byte Wins { get; set; }
        public byte Loses { get; set; }
        public double SuccessRate { get; set; }
        public byte HomeRecord { get; set; }
        public byte RoadRecord { get; set; }
    
        public virtual Conference Conference { get; set; }
        public virtual Team Team { get; set; }
    }
}
